-- INSERT INTO burgers (name, ingredients, eaten)
-- VAULES ('Bacon Attack', 'bacon, bacon, bacon, patty, ketchup, onions, bacon'),
-- VAULES ('Early Riser', 'sunny side up egg, cheese, bacon, ketchup'),
-- VAULES ('Bourbon Glaze', 'bbq sauce, sauteed mushrooms, bacon, cheese, shot of bourbon'),
-- VAULES ('Kid Sized', 'patty, bread')
